# Generated by Django 4.2.4 on 2024-03-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advise', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.student')),
                ('Advising', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.staff')),
            ],
        ),
    ]
