# Generated by Django 4.2.4 on 2024-03-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
            ],
        ),
    ]
