# Generated by Django 4.2.4 on 2024-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretary',
            name='secid',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='staff',
            name='secid',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='stdid',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
