# Generated by Django 4.2.4 on 2024-04-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_advisor_stdid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='Advising',
        ),
    ]
