# Generated by Django 4.2.4 on 2024-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_advisor_advising'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='secid',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
