# Generated by Django 4.2.4 on 2024-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_advisor_secid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='File',
            field=models.FileField(default=None, upload_to='upload'),
        ),
    ]
