# Generated by Django 4.2.4 on 2024-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='File',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
