# Generated by Django 4.2.4 on 2024-04-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploaded',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='stdid',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
