# Generated by Django 4.2.4 on 2024-05-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_vicechairman_chairman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='staf',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.staff'),
        ),
        migrations.AlterField(
            model_name='vicechairman',
            name='staf',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.staff'),
        ),
    ]
