# Generated by Django 4.2.4 on 2024-05-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_chairman_staf_alter_vicechairman_staf'),
    ]

    operations = [
        migrations.CreateModel(
            name='secnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
