# Generated by Django 4.2.4 on 2024-05-05 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_secnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='secnotification',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secnotification',
            name='stdid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
