# Generated by Django 4.2.4 on 2024-05-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_secnotification_date_secnotification_stdid'),
    ]

    operations = [
        migrations.CreateModel(
            name='stdnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=100)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
