# Generated by Django 4.2.4 on 2024-05-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_stdnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdnotification',
            name='stdid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
