# Generated by Django 4.2.4 on 2024-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_stdnotification_stdid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdnotification',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
