# Generated by Django 4.2.4 on 2024-05-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_stdnotification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stdnotification',
            name='type',
        ),
    ]
