# Generated by Django 4.2.4 on 2024-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_secnotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
