# Generated by Django 4.2.4 on 2024-05-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_uploadedfile_location_uploadedfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
