# Generated by Django 4.2.4 on 2024-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_uploadedfile_date_uploadedfile_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='Barcodeimage',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='barcode',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
