# Generated by Django 4.2.4 on 2024-05-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_uploadedfile_barcodeimage_uploadedfile_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='Barcodeimage',
        ),
    ]
