# Generated by Django 4.2.4 on 2024-05-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_remove_uploadedfile_barcodeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='Advisorstatus',
            field=models.CharField(default='Not received', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='chairstatus',
            field=models.CharField(default='Not received', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='vicestatus',
            field=models.CharField(default='Not received', max_length=100),
        ),
    ]
