# Generated by Django 4.2.4 on 2024-05-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_uploadedfile_advisorstatus_uploadedfile_chairstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='flag',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
