# Generated by Django 4.2.4 on 2024-05-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_uploadedfile_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=100)),
                ('Date', models.DateField(auto_now_add=True)),
                ('stdid', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
