# Generated by Django 4.2.4 on 2024-05-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_staffnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='secid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
